### ISSUE TITLE
Unknown rule `@stylistic/declaration-block-single-line-max-declarations`.

### ISSUE THREAD

**Issue by rbnts** [stylelint-stylistic/stylelint-config#1]
The config defines the rule [`@stylistic/declaration-block-single-line-max-declarations`](https://github.com/stylelint-stylistic/stylelint-config/blob/main/.stylelintrc.json#L22C66-L22C66) that doesn't exist in [`@stylistic/stylelint-plugin`](https://github.com/stylelint-stylistic/stylelint-stylistic/blob/main/docs/user-guide/rules.md#declaration-block). This in turn causes Stylelint to freak out and fail. Not sure where this rule came from since it doesn't exist in either [`stylelint-stylistic`](https://github.com/elirasza/stylelint-stylistic) or [`@stylistic/stylelint-plugin`](https://github.com/stylelint-stylistic/stylelint-stylistic).

**Comment by firefoxic** [comment]
Thanks for the report! Already fixing it....

**Comment by firefoxic** [comment]
I made a config based on [this diff](https://github.com/stylelint/stylelint-config-standard/commit/e1d2e98c31cad2320674a0cd058869aa75bd8b14#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346).

And mentioning 64 rules [here](https://github.com/stylelint/stylelint-config-standard/releases/tag/30.0.0) didn't help to detect unnecessary things at an early stage 😒

**Comment by firefoxic** [comment]
@robinloeffel Already in [`v1.0.1`](https://www.npmjs.com/package/@stylistic/stylelint-config/v/1.0.1)

**Comment by rbnts** [comment]
Awesome, thanks!
